### ISSUE TITLE
🐛 Page jumps when using copy button and scrolling

### ISSUE THREAD

**Issue by mbercx** [executablebooks/sphinx-copybutton#106]
**Describe the bug**

When using the copy button, selecting another window and selecting the browser again, everything works fine. However, if I use the copy button and scroll with the trackpad before or after selecting the other window, the page jumps up when I select the browser again:

![out](https://user-images.githubusercontent.com/25607960/100146902-e9f63480-2e9a-11eb-95da-06c996bc3fa1.gif)

Note that here the page jumps to the top, but that isn't always the case. It just always jumps "up".

This was in a local build, but here's a link to a page where these jumps also occur:

https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/tutorial.html

and the corresponding repo:

https://github.com/aiidateam/aiida-core

**Environment**

For the build in the gif:

- Python Version [e.g. 3.7.1]: 3.6.9
- Package versions or output of `jupyter-book --version`: The bug occurs for both `sphinx-copybutton-0.2.12` and `sphinx-copybutton-0.3.1`.
- Operating System: MacOS Mojave Version 10.14.5

**Additional context**

First reported [here](https://github.com/aiidateam/aiida-tutorials/issues/246) by @ltalirz.

**Comment by chrisjsewell** [comment]
Nah don't know what you're talking about 😝

**Comment by mbercx** [comment]
> Nah don't know what you're talking about 😝

😆 Well, you know, no pressure, but if you could fix this before next week's BIGMAP tutorial, that'd be _great_, @chrisjsewell! 😉

**Comment by MegChai** [comment]
> Nah don't know what you're talking about 😝

I met the same situation. Here are steps to reproduce it:

- Click copy button in HTML page;
- Change to other tabs or other programs;
- Come back. Then you will find the page was scrolled up.

**Comment by MegChai** [comment]
> > Nah don't know what you're talking about 😝
> 
> 😆 Well, you know, no pressure, but if you could fix this before next week's BIGMAP tutorial, that'd be _great_, @chrisjsewell! 😉

Hi @mbercx  I find that the copy button seems working fine with the current AliDA doc, could you please tell me how do you solve with it?

**Comment by mbercx** [comment]
@MegChai I didn't solve it myself, but maybe @chrisjsewell did some magic? He's the EB expert in our team. :)

**Comment by mbercx** [comment]
Still a problem on our latest tutorial docs (also on our _main_ documentation, btw). Has anyone looked into a fix for this? It makes presenting for tutorials with the `copybutton` quite confusing. 😅

**Comment by mbercx** [comment]
My workaround for now is just having the habit of clicking an extra time next to the code snippet after copying before I move to another window, that seems to avoid the jumping.

**Comment by akhmerov** [comment]
This is likely due to the implementation of clipboard.js (they had similar issues before: https://github.com/zenorocha/clipboard.js/issues/179). It [creates a textarea](https://github.com/zenorocha/clipboard.js/blob/57345ab3ce1b3526d736e1b391257d7221854513/dist/clipboard.js#L111) to make text copyable, and this is likely what confuses the page positioning.

**Comment by pradyunsg** [comment]
Yea, the solution might be to do #97. 🙃

**Comment by akhmerov** [comment]
It seems to be [this logic](https://github.com/zenorocha/clipboard.js/blob/57345ab3ce1b3526d736e1b391257d7221854513/dist/clipboard.js#L87-L90): the `fakeElement` attached to DOM and selected has to be at the current y-position. Now if only I knew CSS, I would probably be able to understand what goes wrong, however it seems like a hack and a direct JS approach seems more reliable indeed.

**Comment by choldgraf** [comment]
@pradyunsg i am all for it! i just have no idea how to do it haha
