### ISSUE TITLE
copy button <img> doesn't work with dirhtml builder, only on root page

### ISSUE THREAD

**Issue by rkdarst** [executablebooks/sphinx-copybutton#110]
I just submitted a PR, which usually means I was looking for a bug.  Here it is. 

**Describe the bug**

As the title says, adding a literal block block on a Sphinx project's main page, and then building with the `dirhtml` builder, gives you this:

![image](https://user-images.githubusercontent.com/6877977/101370905-caa3d200-38b2-11eb-963b-e543f350c0f7.png)

If you look at the HTML source (after it's been processed by the javascript, so you need to use the element inspector, not 'view source'), you get this:
```html
<img src="#_static/copy-button.svg" alt="Copy to clipboard>
```
So an extra `#` in the `src`, which breaks the link.  If you remove the `#`, it works.

I've tracked it down as best I can, and this is what I have found https://github.com/executablebooks/sphinx-copybutton/blob/38e9b8179370f6438a847c2febc86c4fcbf12b1c/sphinx_copybutton/_static/copybutton.js_t#L79

The `_t` means this is a static theme template, processed by Sphinx (in case anyone is wondering):
https://www.sphinx-doc.org/en/master/development/theming.html?highlight=_t#static-templates
It looks like the syntax `${DOCUMENTATION_OPTIONS.URL_ROOT}` is interpreted on the web browser side.

In fact, you *do* see in the raw HTML this.  So, this is where url_root is set to `#` (this happens in `documentation_options.js`)
```html
    <script id="documentation_options" data-url_root="#" src="_static/documentation_options.js"></script>
```

Grepping the Sphinx source for `url_root`, I see this:
```
sphinx/themes/basic/layout.html:{%- set url_root = pathto('', 1) %}
sphinx/themes/basic/layout.html:{%- if url_root == '#' %}{% set url_root = '' %}{% endif %}
sphinx/themes/basic/layout.html:    <script id="documentation_options" data-url_root="{{ pathto('', 1) }}" src="{{ pathto('_static/documentation_options.js', 1) }}"></script>
```

So actually, it looks like the first two lines are trying to solve this problem, and the third line doesn't use the fix.

The above is as far as I have gone, and am starting to get to the limits of my Sphinx.

The problem does *not* occur with:
* the `html` builder
* an `index.rst` in any subdirectory
* Files named other than `index.rst` in the source root (but note, this is probably not rst-specific).

So actually, it doesn't seem like a sphinx-copybutton problem!

**To Reproduce**

This sample repository reproduces it, it includes requirements.txt file and should be usable
https://github.com/rkdarst/sphinx-copybotton-test-tmp

1. Clone that repo
2. create venv and install requirements
3. `make dirhtml`
4. examine the output in `build`
5. This repository can also be used for debugging, etc.

Alternatively, you can experience this problem live here: https://enccs.github.io/intermediate-mpi/#graphical-and-text-conventions

**Expected behavior**

* `<img src=` is correct
* documentation repo links are above.

**Environment**

- current released `sphinx-copybutton` + `sphinx` is enough to reproduce this, not dependent on Python version (3.7 and 3.8 tested)
- NOT using jupyter-book
- Linux

**Additional context**

This was originally reported here, in the context of sphinx-lesson : https://github.com/coderefinery/sphinx-lesson/issues/50

Although I have found the bug and don't think it is on sphinx-copybutton, I wrote so much I will submit it here for reference, and so that it it is searchable and doesn't get lost.

**Comment by rkdarst** [comment]
Do I need a welcome message for every individual repository, and a different one for PRs and issues, and closing PRs?  But I understand it's nice and probably there isn't a way to make it organization wide...

This is actually a property of the *themes*.  I see the same copy-paste problem with sphinx_rtd_theme (which is what I actually use...).  I haven't investigated sphinx-book-theme yet.

**Comment by rkdarst** [comment]
If you look up you can see the fixes in the themes
Unfortunately there may be other themes that need fixing, but hopefully someone can find it.

**Comment by rkdarst** [comment]
There has been fixed upstream in sphinx and sphinx_rtd_theme.  I think it's not an issue in sphinx-book-theme.  My workaround using `sed` to dynamically fix it in older versions is findable here https://github.com/coderefinery/sphinx-lesson/issues/50 .

**Comment by choldgraf** [comment]
oops sorry I missed this one - so nothing to change in the copybutton codebase?

(and yeah, I'm not sure how to get the bots to track people across repositories within an org :-/ )

**Comment by rkdarst** [comment]
Yes, in the end it was a problem in several upstream themes, and
nothing needs changing in excutablebooks.  Surprisingly, it was a bug
that could have affected very many things, yet was undetected.
Anyway, it was sort of fun to solve.

**Comment by choldgraf** [comment]
> Surprisingly, it was a bug
that could have affected very many things, yet was undetected.

haha I know what you mean - you see the bug and think "there is no way that I am the first one to be affected by this"
