### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by dbitouze** [executablebooks/sphinx-copybutton#113]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be nice for the strings "Copy" and "Copied" to be customizable or, better, to be automatically translated according to the chosen language for the underlying Sphinx documentation.

**Comment by choldgraf** [comment]
I believe that they already are - see here for a list of the supported languages (and the pattern needed to support a new language):

https://github.com/executablebooks/sphinx-copybutton/blob/master/sphinx_copybutton/_static/copybutton.js_t#L3

Gonna close this but please re-open if I've mis-interpreted what you asked!

**Comment by mgeier** [comment]
See also https://github.com/executablebooks/sphinx-togglebutton/issues/22.

**Comment by dbitouze** [comment]
> I believe that they already are - see here for a list of the supported languages (and the pattern needed to support a new language):
> 
> https://github.com/executablebooks/sphinx-copybutton/blob/master/sphinx_copybutton/_static/copybutton.js_t#L3
> 
> Gonna close this but please re-open if I've mis-interpreted what you asked!

OK, just a matter of a missing French translation :smile: I just made a pull request.

Perhaps a dedicated file for translations, with a clear `po/` directory could help future potential translators.
