### ISSUE TITLE
Request ability to selectively disable the copy button for codeblocks

### ISSUE THREAD

**Issue by JMarkstrom** [executablebooks/sphinx-copybutton#117]
I am looking for the ability to _disable_ 'copy' for some code blocks selectively.

An example use case is, I need to show the prompts that an install script makes. 
Those prompts are interesting to see, but there is absolutely no benefit of being able to copy them.
Here is a formatting example where I would want copy on the first code block, but NOT on the second:

1. Run the `FreeRADIUSv3.sh` script by executing the following command:

        sudo sh ./FreeRADIUSv3.sh

2. Press **Enter** when prompted to start the (re)configuration:

:: 

    Provide necessary configurations for FreeRADIUS container to run. Press [Enter] to continue.
3. Do something...

**Comment by choldgraf** [comment]
Hmmm - could you get this to work the way you want by modifying the copybutton selector? https://github.com/executablebooks/sphinx-copybutton/blob/master/sphinx_copybutton/_static/copybutton.js_t#L77

That is what is used to determine whether to copy a cell. You could either add a CSS rule to some cells, and then modify the selector to only select that rule?

**Comment by jamesholland-uk** [comment]
This enhancement would be really great. All code blocks get the copy button, whether it is useful for the user or not, as @JMarkstrom says. Selective disabling of the button would allow us to show outputs of commands and not confuse users into thinking it is something they need to copy/paste. Thanks

**Comment by choldgraf** [comment]
Do the instructions here not work for this? https://sphinx-copybutton.readthedocs.io/en/latest/#configure-the-css-selector-used-to-add-copy-buttons

**Comment by jamesholland-uk** [comment]
Thanks @choldgraf. How do I selectively change the element used for specific code-blocks, the ones I want in include/exclude having the copy button? When I have this in my source:
```
.. code-block::
   
        $ command goes here
```
I looked around and couldn't find a way from reading the docs. Lots of parameters for turning on/off line numbers, highlighting lines, specifying a programming language for the code block, etc but nothing for the HRML element for the code block?

**Comment by choldgraf** [comment]
I believe you can add a class to code blocks like so:

```rst
.. code-block::
   :class: some-class

   print("hi")
```

does that work for you? If so, we can try to add in an example to the docs

**Comment by jamesholland-uk** [comment]
I used this in my conf.py:
```
copybutton_selector = "div.copy-button pre"
```
Then this in the source document:
```
.. code-block::
        :class: copy-buttton
```
And got this in the resulting HTML:
```
<div class="copy-button highlight-default notranslate"><div class="highlight"><pre><span></span>$ some code here</pre></div>
```
And it works 👍  Thanks so much for the assistance @choldgraf!

More documentation would definitely help given my experience, or I'm just new/slow/etc 😆

**Comment by rdauria** [comment]
Hello All, 

While the procedure described by @jamesholland-uk in https://github.com/executablebooks/sphinx-copybutton/issues/117#issuecomment-993499190 works, it is a little impractical as it requires adding: `:class: copy-buttton` under each and every one of the code blocks that should show a copy button. These generally are the vast majority and only sometimes (for example, when displaying a sample output) one would need to remove the copy button. How would I go about to define a class that does not add the copy button? My goal is to add that class solely to the minority of code blocks that do not require the copy button and have copy buttons show in all other cases. 

Thanks!
