### ISSUE TITLE
Copying code blocks with '>>>' prompts

### ISSUE THREAD

**Issue by jmd-dk** [executablebooks/sphinx-copybutton#146]
### Describe the problem

Code blocks within Sphinx recognizes the Python prompt `>>>` (and possible others for other languages) at the beginning of lines. Not only are they color coded, but they are not highlighted if you click and drag the mouse over them. This allows for convenient copying of code from blocks that include such prompt characters, without getting the prompt mixed in with the copied code. Unfortunately, this behavior is not what we get with sphinx-copybutton, which instead includes the prompts in the copy.

### Link to your repository or website

https://jmd-dk.github.io/concept/command_line_options.html#interactive-i-interactive

### Steps to reproduce

1. Consider the very last code block [here](https://jmd-dk.github.io/concept/command_line_options.html#interactive-i-interactive).
2. Try copying the content of the code block using 'click and drag' and right-click + copy (or Ctrl + C). Paste somewhere.
3. Now use the copy button.

### The version of Python you're using

3.9.7

### Your operating system

Linux Mint 20

### Versions of your packages

* Sphinx 4.2.0
* sphinx_copybutton 0.4.0
* sphinx_rtd_theme 1.0.0
* sphinx_tabs 3.2.0

### Additional context

I'm not sure whether this is intended behavior, but I imagine that what the copy button should do in this case perhaps hasn't been addressed at all. I feel that pressing the copy button should always be equivalent to me manually highlighting the entire code block, right-clicking and selecting 'copy'.

**Comment by Loic-R** [comment]
Hello @jmd-dk 
You probably missed the related part of the documentation talking about [how to strip input prompts](https://sphinx-copybutton.readthedocs.io/en/latest/#strip-and-configure-input-prompts-for-code-cells)

In your case, if you're just dealing with python prompts in your documentation, you can simply add `copybutton_prompt_text = ">>> "`  in the conf.py, it's working fine for me

Have a nice day

**Comment by jmd-dk** [comment]
@Loic-R I did indeed miss that. Thanks a lot, works great!
