### ISSUE TITLE
Build failed for config doc when importing an extension sphinx_copybutton

### ISSUE THREAD

**Issue by SinChan4896** [executablebooks/sphinx-copybutton#169]
### Describe the bug

This is the duplicate question, and someone stated need to create the `.readthedocs.yaml` and `requirement.txt` to set the configuration for build.
https://github.com/readthedocs/readthedocs.org/issues/7100

**Problem**
The sphinx_copybutton is working fine in local but failed to build in RTD.

**Error**
`Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')`

**Question**
I follow the Configuration File V2 at the link below: 
https://docs.readthedocs.io/en/stable/config-file/v2.html#formats

![image](https://user-images.githubusercontent.com/84772487/169204959-fcd73ad6-6978-4dfc-a51f-5c74e35a8463.png)

### Reproduce the bug

1. pip install sphinx-copybutton
2. In the `conf.py` add 
extensions = [ ... 'sphinx_copybutton' ... ]

### List your environment

Version: 1.67.1 (user setup)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
--------------------------------------

Package                      ( Version )
alabaster                     0.7.12
appdirs                       1.4.4
Babel                         2.10.1
certifi                       2021.10.8
charset-normalizer            2.0.12
colorama                      0.4.4
docutils                      0.17.1
esbonio                       0.11.2
idna                          3.3
imagesize                     1.3.0
Jinja2                        3.1.2
MarkupSafe                    2.1.1
packaging                     21.3
pip                           22.1
pydantic                      1.8.2
pygls                         0.11.3
Pygments                      2.12.0
pyparsing                     3.0.8
pyspellchecker                0.6.3
pytz                          2022.1
requests                      2.27.1
setuptools                    62.3.1
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinx-bernard-theme          0.1.12
sphinx-copybutton             0.5.0
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
typeguard                     2.13.3
typing_extensions             4.2.0
urllib3                       1.26.9

**Comment by martinbndr** [comment]
@SinChan4896 Is there a chance you have solved this issue? Also facing this issue recently.

**Comment by doyled-it** [comment]
@SinChan4896, @martinbndr: Any fix for this that you've discovered? This just started happening for me and there's no reason as to why this issue was closed.

**Comment by martinbndr** [comment]
> @SinChan4896, @martinbndr: Any fix for this that you've discovered? This just started happening for me and there's no reason as to why this issue was closed.

Yea still occuring for me and idk why they closed it.
