### ISSUE TITLE
feature request: configurability of copyability

### ISSUE THREAD

**Issue by kratsg** [executablebooks/sphinx-copybutton#52]
from scikit-hep/pyhf#721 

> a simple way is to add a configuration to allow for the last line to be copied or skipped. This should handle both cases. Additionally, could add a configuration indicating if the project wants to use >>> and ... so then you can just not copy lines that don't start with that.

In order to be a bit more flexible about how code snippets can be copied, it is true that there is no enforced consistency so that as of right now, the entire code-block is copied. This issue requests two separate things:

1. The ability to toggle on/off whether the last line in a code-block should be copied (this doesn't necessarily assume a language)
1. The ability to toggle on/off whether lines without `>>>` or `...` should be copied (note: this one assumes python)
1. Perhaps in the future, similar to above, the ability to toggle whether lines without `>` or `$` should be copied

**Comment by mgeier** [comment]
I wonder if this effort could be somehow combined with https://github.com/sbrunner/sphinx-prompt?

**Comment by choldgraf** [comment]
What if we just added an extra True/False flag to what we already have, that allows authors to say "if a code block has the `>>>` in it, then *only* copy the lines that start with `>>>` and skip the rest (after stripping the `>>>`).

**Comment by lukasheinrich** [comment]
alternatively some configuration to specify which lines to copy (ignoring all other lines)

```
{"match_lines": ["^>>>","^>..."], strip_match=true}
```

**Comment by choldgraf** [comment]
Just a note for future ref:

To get allow for multiple strings in the `conf.py` value, we should use something like this in the template:

```jinja
{% if copybutton_skip_text is string %}'{{ copybutton_skip_text }}'{% else %}{{ copybutton_skip_text }}{% endif %}
```

**Comment by mgeier** [comment]
As mentioned in #59, I think it would be good to take inspiration from the "copy button" in the Python docs, see e.g. https://docs.python.org/3/tutorial/controlflow.html

The corresponding code is in https://github.com/python/python-docs-theme/blob/master/python_docs_theme/static/copybutton.js

**Comment by chrisjsewell** [comment]
As @lukasheinrich alludes to, the prompts should also be regexes, in particular to handle ipython type prompts:

```python
In [1]: x = 2

In [2]: x**3
Out[2]: 8
```

**Comment by chrisjsewell** [comment]
In fact if its a regex, you don't need to have multiple strings, just e.g.

```python
copybutton_lines_regex = "^(>>>|...|In\s*\[\d*\]\:).*"
```

**Comment by choldgraf** [comment]
I agree with regexes, just haven't had the time so a PR is welcome. I'm not so sure about *forcing* people to use regexes though since most are not comfortable with them

**Comment by chrisjsewell** [comment]
Yes I was thinking this as well: those pesky amateur users! Perhaps keep `copybutton_prompt_text` as is, and converted it on the fly to a regex before injecting into the javascript. Then also have the `copybutton_lines_regex` for "power users" which, if set, will override  `copybutton_prompt_text`

**Comment by choldgraf** [comment]
that makes sense to me 👍

**Comment by lucasrodes** [comment]
just came to this issue when I wanted to have python blocks ('>>>') and bash blocks ('$') in the same documentation.

I think the design idea from @chrisjsewell is great.

**Comment by choldgraf** [comment]
Yep - it sounds like currently this is just waiting on implementation of https://github.com/executablebooks/sphinx-copybutton/issues/52#issuecomment-631526596

**Comment by chrisjsewell** [comment]
Cheers, I'll give it a quick go over the next few days

**Comment by chrisjsewell** [comment]
Ok this is implemented in #82 if you want to give some feedback before I merge

**Comment by stefanodavid** [comment]
Perhaps loosely related to this issue, but is it there a way to configure copy on multi-line bash commands like:
```
curl -X POST -L "https://ww.example-org token" \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=my_username' \
--data-urlencode 'password=my_password' 
```
(if I'm in the wrong place, please advice where to comment, thanks!)

**Comment by amotl** [comment]
Dear @stefanodavid,

what you are referring to here, honoring line continuation characters, has just been implemented by @sappelhoff, see #126. Thanks to @choldgraf, the new feature is already available per `sphinx-copybutton 0.3.3`.

With kind regards,
Andreas.

**Comment by choldgraf** [comment]
indeed I think this one could now be closed! thanks @amotl and @sappelhoff for all your help :-)

**Comment by stefanodavid** [comment]
Thanks @sappelhoff @amotl and @choldgraf, I think that PR #126 covers my use case. I will try to make some test on my code in the next weeks and in the (unlikely) case it does not work, I'll report here.
