### ISSUE TITLE
error with pip-installing

### ISSUE THREAD

**Issue by franconianmetal** [executablebooks/sphinx-copybutton#80]
`pip install sphinx-copybutton`
causes
`ImportError: No module named pathlib`

when I install
`pip install pathlib` and `pip install sphinx-copybutton` this causes
`AttributeError: 'PosixPath' object has no attribute 'read_text'`

my version: python -V -> Python 2.7.17

only working on python3/pip3? If yes pls update documentation for prerequisities.
 I'll try to upgrade my python.

**Comment by franconianmetal** [comment]
working on python3/pip3

pls update documentation for prerequisities

**Comment by choldgraf** [comment]
thanks for noting this - I added a note to the docs
