### ISSUE TITLE
Prompt Regex Escaping Confusion

### ISSUE THREAD

**Issue by s-weigand** [executablebooks/sphinx-copybutton#86]
First of all thanks for the new Prompt RegEx feature ❤️ 
I did just try it out and after some fiddeling around with the escaping, it works like a charm.

## Expected behaviour
First of all I think in some edge cases it  might make a difference to mention that the RegEx you type in your `config.py` is a JS RegEx and not a python one.
So that said IMHO it should work similar to this:

```python
copybutton_prompt_text = r"<valid_js_reg_ex> "
copybutton_prompt_is_regexp = True
```
🌈 🦄  

## What I did

In my case the prompt I wanted to get rid of was of the form 
```python
r"In \[\d*\]: |\.\.\.: "
```
which is the `jupyter console` style and pretty much the same as the iPython style from the docs 
```python 
"\\[\\d*\\]: |\\.\\.\\.: "
```

So it should be straight forward
```python 
"In \\[\\d*\\]: |\\.\\.\\.: "
```
as in the docs and I would be done?

But it didn't work, so I did some digging and ended up with:
```python 
"In \\[\\d*\\]: |\\.\\.\\.: |\\$ "
```

## What internally happens
In my `config.py`, I set `copybutton_prompt_text`
```python
copybutton_prompt_text = r"In \[\d*\]: |\.\.\.: "
```
which is the same as:
```python
copybutton_prompt_text = "In \\[\\d*\\]: |\\.\\.\\.: "
```
```python
>>> r"\\" == "\\\\"
True
```

Sphinx now replaces the context variable [`copybutton_prompt_text`](https://github.com/executablebooks/sphinx-copybutton/blob/d56f2cf69e7ad8346b9dad950b3cd03bdaba2c16/sphinx_copybutton/_static/copybutton.js_t#L89) in `copybutton.js_t` and generates `copybutton.js`.
But when we look at that string which should have just been passed as is, it is missing backslashes.
```javascript
'In \[\d*\]: |\.\.\.: |\$ '
```

Well this looks like a totaly valid JS RegEx, so this is fine?
And it would be if written like this (JS just wants keep people on their toes, so why not a different character for RegEx strings?):
```javascript
/In \[\d*\]: |\.\.\.: |\$ /
```

Now the string [gets passed to the RegExp constuctor](https://github.com/executablebooks/sphinx-copybutton/blob/d56f2cf69e7ad8346b9dad950b3cd03bdaba2c16/sphinx_copybutton/_static/copybutton_funcs.js#L14), which [expects strings to be escaped](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Flags_in_constructor) like python, if you don't use raw strings.
But it doesn't match.

```javascript
> "In [1]: bar".match(new RegExp('^(In \[\d*\]: |\.\.\.: )(.*)'))
null
```

#### TLDR
IMHO this all comes down ro JS RegExp 'helping' you in some cases when it can interprete what you might have ment, which gives you false security (false positiv match in the tests).

#### Details
Disclaimer I'm in no way a JS expert with insight into the internals, I just found this due to WTF moments + trail and error.

```javascript
> let proper_regex = new RegExp('^(>>> |\\$ |In \\[\\d*\\]: |\\[\\d*\\]: |\\.\\.\\.: )(.*)')
undefined
> let false_positive_regex = new RegExp('^(>>> |\\$ |In \[\d*\]: |\[\d*\]: |\.\.\.: )(.*)')
undefined
>"$ bar".match(proper_regex)
(3) ["$ bar", "$ ", "bar", index: 0, input: "$ bar", groups: undefined]
> "[1]: bar".match(proper_regex)
(3) ["[1]: bar", "[1]: ", "bar", index: 0, input: "[1]: bar", groups: undefined]
> "[1]: bar".match(false_positive_regex)
(3) ["[1]: bar", "[1]: ", "bar", index: 0, input: "[1]: bar", groups: undefined]
> "...: bar".match(proper_regex)
(3) ["...: bar", "...: ", "bar", index: 0, input: "...: bar", groups: undefined]
> "...: bar".match(false_positive_regex)
(3) ["...: bar", "...: ", "bar", index: 0, input: "...: bar", groups: undefined]
```
So far so good, all [testcases](https://github.com/executablebooks/sphinx-copybutton/blob/master/sphinx_copybutton/_static/test.js) work fine, as we would expect since they pass.

```javascript
> "In [1]: bar".match(proper_regex)
(3) ["In [1]: bar", "In [1]: ", "bar", index: 0, input: "In [1]: bar", groups: undefined]
> "In [1]: bar".match(false_positive_regex)
null
```

The only explaination I got for this behaviour, is that JS wants to "help" the user by guessing it's intention, like the famous adding thingy:
 ```javascript
> "5" + 1
"51"
```

but at some points it is like "I don't get it", and the pattern that worked before fails.

#### Use `repr` in `add_to_context`
If [this line](https://github.com/executablebooks/sphinx-copybutton/blob/d56f2cf69e7ad8346b9dad950b3cd03bdaba2c16/sphinx_copybutton/__init__.py#L19) was changed to:
  ```python
        {"copybutton_prompt_text": r"{}".format(repr(config.copybutton_prompt_text))[1: -1]}
  ```
I know it looks ugly, but would add extra backslashes for escaping (maybe someone else has a more elegant solution). 
I'm not sure how much [`escapeRegExp`](https://github.com/executablebooks/sphinx-copybutton/blob/d56f2cf69e7ad8346b9dad950b3cd03bdaba2c16/sphinx_copybutton/_static/copybutton_funcs.js#L1) would need to be adjusted to those changes.

I didn't have luck with backslash replacing in JS:
```javascript
> 'In \[\d*\]: |\.\.\.: '.replace(/\\/, '\\\\');
"In [d*]: |...: "
> 'In \[\d*\]: |\.\.\.: '
"In [d*]: |...: "
```

So in conclusion:
Python ❤️ 
JS 😠 

P.S.: Wish we had the `sphinx-copybutton` on github, for the JS blobs I posted 😢

**Comment by choldgraf** [comment]
hmmmm - a couple quick thoughts:

* Maybe @chrisjsewell can advise on whether the regexp behavior you're describing looks like a JS thing, or maybe it's a Jinja thing? If it's a Jinja thing then I think we can try to design around this in other ways.
* @s-weigand would you be interested in making a PR to the docs with some "sample" regexes that will match very common patterns? E.g., the `In[*]` and `Out[*]` pattern? That could be helpful in saving people time in the future!

**Comment by s-weigand** [comment]
I can make a PR at the weekend, maybe we even get the escaping thingy resolved by then. 😄 

What definitely is a JS thing is that two different regexs match the same string.

Ha I just found tha jinja2 has the [format filter builtin](https://jinja.palletsprojects.com/en/2.11.x/templates/?highlight=filter#format).

so changing:
https://github.com/executablebooks/sphinx-copybutton/blob/d56f2cf69e7ad8346b9dad950b3cd03bdaba2c16/sphinx_copybutton/_static/copybutton.js_t#L89

to:
```javascript
  return formatCopyText(target.innerText, {{ "{!r}".format(copybutton_prompt_text) }}, {{ copybutton_prompt_is_regexp | lower }}, {{ copybutton_only_copy_prompt_lines | lower }},  {{ copybutton_remove_prompts | lower }})
```

Also does the trick, looks nicer and should be more reliable than my repr solution.
If this looks fine to you I can make the PR for docs and the template.

**Comment by chrisjsewell** [comment]
> Ha I just found tha jinja2 has the format filter builtin.

Ah cool didn't notice that, yep that looks like it should improve the issue thanks @s-weigand, all them backslashes are a right pain

**Comment by choldgraf** [comment]
nice catch @s-weigand !
